/**
 * Zolto Phase 8 Unit & Integration Test Suite — Spatial Layout & Canvas Engine
 */

import { compile, parse, render, parseLayout, renderLayout, validateDiagram, validateChart, validateVector, validateLayout as zoltoValidateLayout } from '../src/zolto.js';
import { validateLayout } from '../src/layout/validator.js';

let passed = 0;
let failed = 0;

function assert(condition, message) {
  if (condition) {
    passed++;
    console.log(`    ✓ ${message}`);
  } else {
    failed++;
    console.error(`    ❌ ${message}`);
  }
}

function contains(html, str) {
  assert(typeof html === 'string' && html.includes(str), `HTML contains '${str.slice(0, 50)}'`);
}

export function runPhase8Tests() {
  passed = 0;
  failed = 0;

  console.log('\nPhase 8 · Spatial Layout & Canvas Engine Suite');

  // 1. Top-Level Layout Directive
  console.log('\n  1. Top-Level Layout & Structure');
  const src1 = `@layout width=1200 padding=24 gap=16
@header
# Report Header
@/header
@main
Main content paragraph.
@/main
@footer
Generated by Zolto
@/footer
@/layout`;
  const html1 = compile(src1);
  contains(html1, 'zl-layout-container');
  contains(html1, 'zl-layout-header');
  contains(html1, 'Report Header');
  contains(html1, 'zl-layout-main');
  contains(html1, 'Main content paragraph');
  contains(html1, 'zl-layout-footer');

  // 2. Grid Layout & Cell Spans
  console.log('\n  2. Grid Layout & Cell Spans');
  const src2 = `@grid columns=12 gap=20
@cell span=4
Left Sidebar
@/cell
@cell span=8
Main Article
@/cell
@/grid`;
  const html2 = compile(src2);
  contains(html2, 'zl-layout-grid');
  contains(html2, 'grid-template-columns: repeat(12, minmax(0, 1fr));');
  contains(html2, 'grid-column: span 4;');
  contains(html2, 'grid-column: span 8;');

  // 3. Grid Named Areas
  console.log('\n  3. Grid Named Areas');
  const src3 = `@grid columns=3 areas="header header header\nsidebar main main"
@cell area="header"
Top Header
@/cell
@cell area="sidebar"
Side Nav
@/cell
@/grid`;
  const html3 = compile(src3);
  contains(html3, 'grid-template-areas: &quot;header header header&quot; &quot;sidebar main main&quot;');
  contains(html3, 'grid-area: header;');
  contains(html3, 'grid-area: sidebar;');

  // 4. Flex Layout & Items
  console.log('\n  4. Flex Layout & Flexbox Items');
  const src4 = `@flex direction="row" justify="space-between" align="center" gap=16
@item grow=1
Item One
@/item
@item basis=240
Item Two
@/item
@/flex`;
  const html4 = compile(src4);
  contains(html4, 'zl-layout-flex');
  contains(html4, 'flex-direction: row;');
  contains(html4, 'justify-content: space-between;');
  contains(html4, 'flex: 1 1 auto;');
  contains(html4, 'flex: 0 1 240px;');

  // 5. Stack Layout
  console.log('\n  5. Stack Layout');
  const src5 = `@stack mode="overlay"
@item z=1
Base layer
@/item
@item z=2
Floating tag
@/item
@/stack`;
  const html5 = compile(src5);
  contains(html5, 'zl-layout-stack');
  contains(html5, 'position: relative; display: block;');

  // 6. Canvas & Absolute Positioning
  console.log('\n  6. Canvas & Absolute Positioning');
  const src6 = `@canvas width=1920 height=1080 snap=8
@layer id="background" z=0
@rect x=0 y=0 w=1920 h=1080 fill="#111111"
@/rect
@/layer
@layer id="title" z=10
@text x=120 y=120 size=64
Title Text
@/text
@/layer
@/canvas`;
  const html6 = compile(src6);
  contains(html6, 'zl-layout-canvas');
  contains(html6, 'width: 1920px; height: 1080px;');
  contains(html6, 'zl-canvas-layer');
  contains(html6, 'z-index: 10;');
  contains(html6, 'Title Text');

  // 7. Pages & Print Layout
  console.log('\n  7. Pages & Print Layout');
  const src7 = `@pages size="A4" margin=32
@page number=1
Page 1 Content
@/page
@page break=always
Page 2 Content
@/page
@/pages`;
  const html7 = compile(src7);
  contains(html7, 'zl-layout-pages');
  contains(html7, 'zl-layout-page');
  contains(html7, 'width: 210mm;');
  contains(html7, 'min-height: 297mm;');
  contains(html7, 'page-break-before: always;');

  // 8. Presentation & Slide Deck
  console.log('\n  8. Presentation & Slide Deck Layout');
  const src8 = `@presentation theme="dark" ratio="16:9"
@slide type="title"
# Presentation Title
@/slide
@slide type="content"
Slide content here.
@/slide
@/presentation`;
  const html8 = compile(src8);
  contains(html8, 'zl-layout-presentation');
  contains(html8, 'zl-layout-slide');
  contains(html8, 'width: 960px; height: 540px;');
  contains(html8, 'Presentation Title');

  // 9. Integration with Math, Diagrams, Charts, and Vectors inside Layout
  console.log('\n  9. Subsystem Integration inside Layout');
  const src9 = `@layout
@grid columns=2 gap=16
@cell
$E = mc^2$
@/cell
@cell
@chart bar
labels: A B
data: 10 20
@/chart
@/cell
@cell
@diagram flowchart
NodeA -> NodeB
@/diagram
@/cell
@cell
@vector width=200 height=100
rect x=0 y=0 w=200 h=100 fill="#7c5cff"
@/vector
@/cell
@/grid
@/layout`;
  const html9 = compile(src9);
  contains(html9, 'zl-layout-container');
  contains(html9, 'zl-math-inline');
  contains(html9, 'svg');
  contains(html9, 'rect');

  // 10. Layout Validation & Deep Probes
  console.log('\n  10. Layout Validation & Diagnostics');
  const { ast: ast10 } = parseLayout('@cell\nBroken cell\n@/cell', '@cell');
  const diag10 = validateLayout(ast10);
  assert(diag10.hasErrors(), 'Validation detects @cell outside @grid');

  const { ast: ast10b } = parseLayout('@grid columns=3\n@cell span=0\nCell\n@/cell\n@/grid');
  const diag10b = validateLayout(ast10b);
  assert(diag10b.warnings.some(w => w.code === 'W805'), 'Validation warns on span <= 0');

  // 11. Public API & Subsystem Validator Exports
  console.log('\n  11. Public API & Subsystem Re-exports');
  assert(typeof validateDiagram === 'function', 're-exports validateDiagram');
  assert(typeof validateChart === 'function', 're-exports validateChart');
  assert(typeof validateVector === 'function', 're-exports validateVector');
  assert(typeof zoltoValidateLayout === 'function', 're-exports validateLayout');

  // 12. Indented Nested Block Parsing & Canvas Text Styling
  console.log('\n  12. Indented Block Parsing & Canvas Text Styling');
  const src12 = `@layout
  @header
    # Indented Header Title
  @/header
  @grid columns=2
    @cell
      ### Indented Cell Subheading
      @card title="Nested Card"
        Card body text
      @/card
    @/cell
  @/grid
@/layout`;
  const html12 = compile(src12);
  contains(html12, '<h1 id="indented-header-title">Indented Header Title</h1>');
  contains(html12, '<h3 id="indented-cell-subheading">Indented Cell Subheading</h3>');
  contains(html12, 'zl-card-title">Nested Card</span>');

  const src12b = `@canvas width=400 height=200
  @layer id="l1"
    @text x=10 y=20 size=24 fill="#00ff00"
      Canvas Text
    @/text
  @/layer
@/canvas`;
  const html12b = compile(src12b);
  contains(html12b, 'color: #00ff00;');
  contains(html12b, 'font-size: 24px;');
  contains(html12b, 'background: transparent;');

  // 13. Performance Benchmark
  console.log('\n  13. Performance Benchmark');
  const cells = Array.from({ length: 100 }, (_, i) => `@cell span=1\nCell ${i}\n@/cell`).join('\n');
  const src11 = `@grid columns=10 gap=8\n${cells}\n@/grid`;
  const start = performance.now();
  const html11 = compile(src11);
  const elapsed = performance.now() - start;
  assert(elapsed < 100, `Parses and renders 100 cells in ${elapsed.toFixed(2)}ms (< 100ms)`);
  contains(html11, 'Cell 99');

  return { passed, failed, total: passed + failed };
}

